version: '3'

services:
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build:
      context: ./web
    ports:
      - "80:80"
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: experiment
    ports:
      - "5432:5432"